from __future__ import annotations


DEFAULT_SELECTORS = {
    "page_ready": [
        "[data-testid='speedgrader-feedback']",
        "#speedgrader",
        "#content",
        "body",
    ],
    "assignment_title": [
        "#assignment_name",
        "#assignment_title",
        ".assignment-title",
        ".assignment-title__title",
        "h1",
    ],
    "student_name": [
        ".student-name",
        "#students_selectmenu-button",
        ".student_name",
    ],
    "grade_input": [
        "input[data-testid='grade-input']",
        "#grading-box-extended",
        "#grading-box",
        "input[name='grade']",
        "input[aria-label='Grade']",
        "input[placeholder*='Grade']",
    ],
    "rubric_button": [
        "button:has-text('View Rubric')",
        "a:has-text('View Rubric')",
        "button:has-text('Show Rubric')",
        "[data-testid='rubric-button']",
        "[data-testid='rubric-assessment-button']",
        "button[aria-label*='Rubric']",
        "button:has-text('Rubric')",
        "a:has-text('Rubric')",
        "button[aria-controls*='rubric']",
        "button[aria-haspopup='dialog']:has-text('Rubric')",
        "button[id*='rubric']",
        "[data-testid*='rubric']",
    ],
    "rubric_panel": [
        "[data-testid='rubric-assessment']",
        "[data-testid*='rubric']",
        "[role='dialog']:has-text('Rubric')",
        ".rubric-assessment",
        ".rubric_container",
        ".Rubric",
    ],
    "rubric_row": [
        "[data-testid='rubric-criterion']",
        ".rubric__criterion",
        ".rubric_criterion",
        "tr",
        "li",
    ],
    "rubric_points_input": [
        "input[data-testid^='criterion-score-']",
        "input[data-testid='rubric-criterion-points']",
        "input[name*='points']",
        "input[aria-label*='points']",
        "input[type='number']",
        "input[type='text']",
    ],
    "rubric_comment_input": [
        "textarea[data-testid^='criterion-comment-']",
        "[data-testid^='criterion-comment-'] textarea",
        "textarea[data-testid='rubric-criterion-comment']",
        "textarea[name*='comment']",
        "textarea[aria-label*='comment']",
        "textarea",
    ],
    "rubric_save": [
        "button[data-testid='save-rubric-assessment-button']",
        "button:has-text('Submit Assessment')",
        "button[aria-label*='Save']",
        "button:has-text('Save')",
        "button:has-text('Update')",
        "button:has-text('Apply')",
    ],
    "comment_box": [
        "textarea[data-rich_text='true']",
        "[data-testid='assignment-comment-input'] textarea",
        "#submission_comment",
        "textarea[name='comment[text_comment]']",
        "textarea[aria-label='Comment']",
        "textarea[placeholder*='Comment']",
        "textarea",
    ],
    "comment_iframe": [
        "[data-testid='assignment-comment-input'] iframe",
        "iframe[id^='rce-']",
    ],
    "comment_submit": [
        "button[data-testid='submit-comment-button']",
        "#comment_submit_button",
    ],
    "save_indicator": [
        ".saving",
        ".saved",
        "[data-testid='speedgrader-feedback']",
        "[data-testid='assessment']",
        "#content",
        "body",
    ],
    "submission_attachments_container": [
        "[data-testid='submission-attachments-container']",
    ],
    "submission_attachments_list": [
        "[data-testid='submission-attachments']",
    ],
    "submission_attachment_link": [
        "button[data-testid^='submission-attachment-link-']",
        "[data-testid^='submission-attachment-link-']",
    ],
    "submission_preview_iframe": [
        "iframe#submission-preview-iframe",
        "iframe[name='submission-preview-iframe']",
    ],
    "annotation_toolbar": [
        "nav.AnnotationControls",
        ".AnnotationControls",
        "#viewer-annotation-toolbar",
        "#annotation-tools",
        ".AnnotationToolbar",
        "[data-testid='annotation-toolbar']",
    ],
    "annotation_zoom_out": [
        "button[aria-label='Zoom Out']:not([disabled]):not([aria-disabled='true'])",
        "button[aria-label*='Zoom Out']:not([disabled]):not([aria-disabled='true'])",
        "button[title='Zoom Out']:not([disabled]):not([aria-disabled='true'])",
        "button[title*='Zoom Out']:not([disabled]):not([aria-disabled='true'])",
        "button[aria-label='Zoom Out']",
        "button[aria-label*='Zoom Out']",
        "button[title='Zoom Out']",
        "button[title*='Zoom Out']",
        "button[data-testid='zoom-out']",
        "button[data-testid*='zoom-out']",
        "button[class*='zoom-out']",
        "button[aria-label='Decrease zoom']",
        "button[aria-label*='Decrease zoom']",
    ],
    "annotation_canvas": [
        ".Page-container",
        "[data-page-number]",
        "[class*='Page-container']",
        ".Draw",
        ".PDFAnnotationLayer-container .annotationLayer",
        ".annotationLayer",
        "canvas.annotationLayer",
        "canvas",
    ],
    "annotation_page": [
        "#page-{page_zero_based}",
        "[data-pagenumber='{page_zero_based}']",
        "[data-page-number='{page}']",
        ".Page-container:nth-of-type({page}) .annotationLayer",
        ".Page-container:nth-of-type({page}) canvas.pageContainer",
        ".Page-container:nth-of-type({page}) canvas",
        ".Page-container:nth-of-type({page}) .Page.PageComponent",
        "[class*='Page-container']:nth-of-type({page})",
        ".Page-container:nth-of-type({page})",
        ".Page-container:nth-of-type({page}) .Draw",
    ],
    "annotation_select": [
        "button[aria-label='Enter selection mode']",
        "button[title='Selection']",
    ],
    "annotation_point": [
        "button[aria-label='Point annotation']",
        "button[title='Point annotation']",
    ],
    "annotation_free_draw": [
        "button[title='Free draw annotation']",
        "button[aria-label*='Free draw']",
        "button[title*='Free draw']",
        "[data-tool='free_draw']",
        "[data-tool='freedraw']",
        "[data-crocodoc-tool='free_draw']",
    ],
    "annotation_strike": [
        "button[title='Strikeout annotation']",
        "button[aria-label*='Strike']",
        "button[title*='Strike']",
        "[data-tool='strikeout']",
        "[data-tool='strike']",
        "[data-crocodoc-tool='strikeout']",
    ],
    "annotation_highlight": [
        "button[title='Highlight annotation']",
        "button[aria-label*='Highlight']",
        "button[title*='Highlight']",
        "[data-tool='highlight']",
        "[data-tool='highlighter']",
        "[data-crocodoc-tool='highlight']",
    ],
    "annotation_freetext": [
        "button[title='Freetext annotation']",
        "button[aria-label*='Freetext']",
    ],
    "annotation_area": [
        "button[title='Area annotation']",
        "button[aria-label*='Area']",
    ],
    "annotation_color_button": [],
    "annotation_color_red": [
        "button.ColorButton[title='Red']",
        "button.ColorButton[aria-label*='Red']",
        "button[aria-label*='Red']",
        "button[title*='Red']",
    ],
    "annotation_color_orange": [
        "button.ColorButton[title='Orange']",
        "button.ColorButton[aria-label*='Orange']",
        "button[aria-label*='Orange']",
        "button[title*='Orange']",
    ],
    "annotation_color_yellow": [
        "button.ColorButton[title='Yellow']",
        "button.ColorButton[aria-label*='Yellow']",
        "button[aria-label*='Yellow']",
        "button[title*='Yellow']",
    ],
    "annotation_color_brown": [
        "button.ColorButton[title='Brown']",
        "button.ColorButton[aria-label*='Brown']",
        "button[aria-label*='Brown']",
        "button[title*='Brown']",
    ],
    "annotation_color_green": [
        "button.ColorButton[title='Green']",
        "button.ColorButton[aria-label*='Green']",
        "button[aria-label*='Green']",
        "button[title*='Green']",
    ],
    "annotation_color_blue": [
        "button.ColorButton[title='Blue']",
        "button.ColorButton[aria-label*='Blue']",
        "button[aria-label*='Blue']",
        "button[title*='Blue']",
    ],
    "annotation_color_dark_blue": [
        "button.ColorButton[title='Dark Blue']",
        "button.ColorButton[aria-label*='Dark Blue']",
        "button[aria-label*='Dark Blue']",
        "button[title*='Dark Blue']",
    ],
    "annotation_color_pink": [
        "button.ColorButton[title='Pink']",
        "button.ColorButton[aria-label*='Pink']",
        "button[aria-label*='Pink']",
        "button[title*='Pink']",
    ],
    "annotation_color_purple": [
        "button.ColorButton[title='Purple']",
        "button.ColorButton[aria-label*='Purple']",
        "button[aria-label*='Purple']",
        "button[title*='Purple']",
    ],
    "annotation_color_black": [
        "button.ColorButton[title='Black']",
        "button.ColorButton[aria-label*='Black']",
        "button[aria-label*='Black']",
        "button[title*='Black']",
    ],
    "annotation_draft_checkbox": [
        "label:has-text('Do not show again for this assignment') input",
        "input[type='checkbox']",
    ],
    "annotation_draft_modal": [
        "[role='dialog']:has-text('draft')",
        "[role='dialog']:has-text('comment')",
        "[role='alertdialog']:has-text('draft')",
        "[role='alertdialog']:has-text('comment')",
        "div:has-text('Do not show again for this assignment')",
        "div:has-text('Proceed')",
    ],
    "annotation_draft_proceed": [
        "button:has-text('Proceed')",
        "button[aria-label='Proceed']",
    ],
}

FIREWORKS_VISION_MAX_IMAGES = 30
FIREWORKS_VISION_MAX_TOTAL_BASE64 = 10_000_000
